version: '3.8'
services:
  xr_vision:
    build: .
    container_name: xr_app
    network_mode: host
    privileged: true  # 하드웨어(USB, IMU) 접근을 위해 필수
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=$DISPLAY
    devices:
      - "/dev/video0:/dev/video0"
      - "/dev/video1:/dev/video1"
      - "/dev/video2:/dev/video2"
      - "/dev/video3:/dev/video3"
    stdin_open: true # 터미널 입력을 받기 위해 필수
    tty: true        # 터미널 입력을 받기 위해 필수